---
title: "Part 2.2 - SNV statistics"
author: "Jörg Wennmann"
date: "2024-12-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Required libraries

```{r}
library(ggplot2)
library(patchwork)
```

#----------

## Input SNV  (read txt)

```{r}
read_snp_matrices <- function(folder_path) {
  file_paths <- list.files(folder_path, pattern = "\\.txt$", full.names = TRUE)
  snp_matrices <- list()

  for (file_path in file_paths) {
    file_name <- sub("\\.txt$", "", basename(file_path))
    snp_matrix <- read.table(file_path, 
                         header = TRUE,        # Spaltennamen vorhanden
                         sep = "\t",           # Tabulator-getrennt
                         stringsAsFactors = FALSE, 
                         check.names = FALSE)
    snp_matrix[snp_matrix == "X"] <- ""
    # Convert to matrix to retain the original format
    snp_matrices[[file_name]] <- as.matrix(snp_matrix)
  }

  return(snp_matrices)
}

folder_path <- "snp_matrix/"
snp_matrices <- read_snp_matrices(folder_path)
snp_matrices[[1]][1:5, 1:20]
```

## Input SNV  (read Rdata)

```{r}
#Or read as Rdata (= list)
load("snp_matrix/snp_matrices.RData")
names(snp_matrices) <- c("snp_matrix_SRR26992682", "snp_matrix_SRR26992684")
```

#----------

## Filter by minimal number covered SNP positions

```{r}
filter_by_no_SNV_positions <- function(m, numberPositions){
  
  funEmpty <- function(x){
    sum(x == "")
  }
  
  funNoPositions <- function(x){
    sum(table(x))
  }
  
  empty <- apply(m, 1, funEmpty)
  totalPositions <- apply(m, 1, funNoPositions)
  
  positionsCovered <- totalPositions-empty
  
  m_filtered <- m[which(positionsCovered >= numberPositions), ]
  
  return(m_filtered)
}

snp_matrices_filtered <- list()
for(i in seq_along(snp_matrices)){
  mat <- snp_matrices[[i]]
  mat <- filter_by_no_SNV_positions(mat, 10)
  snp_matrices_filtered[[names(snp_matrices)[i]]] <- mat
}

snp_matrices <- snp_matrices_filtered

save(snp_matrices_filtered, file = "snp_matrix/snp_matrices_filtered.RData")
```


#----------

## Position Weight Matrix 

```{r}
getPWM = function( seqs, sym=c("A","C","G","T","-") ) {
	t(apply(seqs, 2, function(nuc) {
		idx=which(nuc!="")
		t=table(nuc[idx])
		d=t[sym]
		d[which(is.na(d))] = 0
		names(d)=sym;
		return(d/sum(t))
	} ))
}

pwm_list <- list()

pwm_list <- list()
for (i in seq_along(snp_matrices_filtered)) {
  seqs <- snp_matrices_filtered[[i]]
  
  pwm <- getPWM(seqs)
  pwm_list[[names(snp_matrices_filtered)[i]]] <- pwm
}

pwm_list[["snp_matrix_SRR26992684"]][1:15,]
```
### PWM frequency sorted

```{r}
# Schritt 2: PWMs sortieren und in separater Liste speichern
pwm_list_sorted <- list()
for (i in seq_along(pwm_list)) {
  pwm <- pwm_list[[i]]
  pwm_sorted <- t(apply(pwm, 1, sort, decreasing = TRUE))
  pwm_list_sorted[[names(pwm_list)[i]]] <- pwm_sorted
}

head(pwm_list_sorted[["snp_matrix_SRR26992682"]])
head(pwm_list_sorted[["snp_matrix_SRR26992684"]])
```

## Empirical cumulative distribution function (ECDF)

```{r}
ecdf_plot <- function(pwm){
  
  p <- ggplot() + 
    geom_vline(xintercept = 0, linetype='dashed', color='grey') +
    geom_vline(xintercept = 1, linetype='dashed', color='grey') +
    geom_hline(yintercept = 0, linetype='dashed', color='grey') +
    geom_hline(yintercept = 1, linetype='dashed', color='grey') +
    stat_ecdf(aes(pwm[,4]), col="blue") +
    stat_ecdf(aes(pwm[,3]), col="green") +
    stat_ecdf(aes(pwm[,2]), col="red") +
    stat_ecdf(aes(pwm[,1]), col="black") +
    theme(
      axis.text.x = element_text(),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      axis.line = element_line(colour = "black"),
      panel.background = element_rect(fill = "white"),
      panel.border = element_rect(colour = "black", fill= NA, linewidth = 1),
      legend.position = "none"
    ) +
    theme(
      strip.background = element_blank(),
      strip.text.x = element_blank()
    ) +
    xlab("Relative nucleotide frequency") +
    ylab("% of SNV positions")
  
  return(p)
}


p1 <- ecdf_plot(pwm_list_sorted[["snp_matrix_SRR26992684"]])
p2 <- ecdf_plot(pwm_list_sorted[["snp_matrix_SRR26992682"]])

## combined plot with patchwork
combined_plot <- (p1 | p2) +
  plot_annotation(title = '') +
  plot_annotation(tag_levels = 'A')

print(combined_plot)

f <- 1

w <- 7
h <- 3.5

ggsave("figures/ecdf.png", plot = combined_plot, width = w * f, height = h * f)
```

# Save PWM matrices

The PWM are saved as CVS files and one .Rdata file for easier import.

```{r}
write.csv(pwm_list_sorted[[1]], file = "pwm/pwm_matrix_sorted_SRR26992682.csv", row.names = TRUE)

write.csv(pwm_list_sorted[[2]], file = "pwm/pwm_matrix_sorted_SRR26992684.csv", row.names = TRUE)

save(pwm_list_sorted, file = "pwm/pwm_list_sorted.RData")
```

